from _typeshed import Incomplete
from ranger import VERSION as VERSION

LOG: Incomplete
VERSION_MSG: Incomplete

def main(): ...
def get_paths(args): ...
def xdg_path(env_var): ...
def parse_arguments(): ...

COMMANDS_EXCLUDE: Incomplete

def load_settings(fm, clean): ...
def allow_access_to_confdir(confdir, allow) -> None: ...
