from _typeshed import Incomplete
from ranger.container import settings as settings
from ranger.container.history import History as History
from ranger.core.shared import FileManagerAware as FileManagerAware, SettingsAware as SettingsAware

class Tab(FileManagerAware, SettingsAware):
    thisdir: Incomplete
    history: Incomplete
    last_search: Incomplete
    pointer: int
    path: Incomplete
    pathway: Incomplete
    def __init__(self, path) -> None: ...
    thisfile: Incomplete
    def at_level(self, level): ...
    def get_selection(self): ...
    def assign_cursor_positions_for_subdirs(self) -> None: ...
    def ensure_correct_pointer(self) -> None: ...
    def history_go(self, relative) -> None: ...
    def inherit_history(self, other_history) -> None: ...
    def enter_dir(self, path, history: bool = True): ...
