decoration {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    rounding = 5

    dim_inactive = false
    dim_strength = 0.1
    dim_special = 0.8

    shadow {
      enabled = false
    }

    blur {
        enabled = false
        size = 6
        passes = 3
        new_optimizations = true
        ignore_opacity = true
        xray = true
        special = true
    }
}
