# Example windowrule v1
# windowrule = float, ^(kitty)$
# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
windowrulev = match:class .* suppressevent maximize # You'll probably like this.

$window_rules_conf = $config_path/window_rules

source = $window_rules_conf/*.conf

windowrule = match:class ^(download)$, size 800 600
windowrule = match:class ^(Open|Save File)$, size 800 600

windowrule = match:title (), pin on
windowrule = match:title (), no_shadow on
windowrule = match:title (), no_blur on
