[v1]
"exa 0.10.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["exa"]
"starship 1.16.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["starship"]
"vivid 0.9.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["vivid"]
