---
- name: Localhost setup
  hosts: localhost
  tasks:
    - name: Include Fedora specific roles
      ansible.builtin.include_role:
        name: "{{ item }}"
      loop:
        - copr_repos
        - rpmfusion
        - git_lfs
      when: ansible_os_family == 'RedHat'
  roles:
    - common
    - packages
    - flatpak
    - asdf
    - nvim
    - stow
    - sway
    - greetd
    - vagrant
