---
- name: Localhost setup
  hosts: localhost
  vars:
    desktop_wm: "Hyprland"
    dotfiles_dir: "{{ ansible_env.HOME }}/dotfiles"
    dev_path: "{{ ansible_env.HOME }}/Development"

  roles:
    - setup
    - asdf
    - packages
    - pipewire
    - gpu
    - nvim
    - stow
    - python
    - rofi-calc
    - user
    - greetd
    - ssh
    - vagrant
