---
- name: Localhost setup
  hosts: localhost
  roles:
    - common
    - copr_repos
    - git_lfs
    - rpmfusion
    - packages
    - flatpak
    - asdf
    - nvim
    - stow
    - sway
    - greetd
