---
- name: Localhost setup
  hosts: localhost

  roles:
    - common
    - packages
    - flatpak
    - asdf
    - nvim
    - stow
    - sway
    - rofi-calc
    - greetd
    - vagrant
    - user
    - ssh
