---
# tasks file for user
- name: Change user shell to /usr/bin/zsh
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    shell: /usr/bin/zsh

- name: Handle Fedora Dependencies
  become: true
  ansible.builtin.package:
    name:
      - sassc
      - libsass
    state: present

- name: Install Tokyonight GTK Theme
  vars:
    temp_dir: /tmp/tokyonight_theme
  block:
    - name: Clone Repo
      ansible.builtin.git:
        repo: "{{ user_tokyonight_gtk_theme_url }}"
        depth: 1
        version: master
        dest: "{{ temp_dir }}"

    - name: Install Tokyonight GTK Theme
      vars:
        theme_color: dark
        theme_tweaks:
          - storm
          - outline
          - macos
      ansible.builtin.command: "{{ temp_dir }}/themes/install.sh --color {{ theme_color }} --tweaks {{ theme_tweaks | join(' ') }} --libadwaita"
      args:
        creates: "{{ ansible_env.HOME }}/.themes/Tokyonight-Dark-Storm"

    - name: Cleanup Repo
      ansible.builtin.file:
        path: "{{ temp_dir }}"
        state: absent

- name: Ensure that the icons folder exists
  ansible.builtin.file:
    path: "{{ user_icons_path }}"
    state: directory
    mode: '0755'

- name: Download and Extract theme archive
  ansible.builtin.unarchive:
    src: "https://github.com/ljmill/tokyo-night-icons/releases/download/v0.2.0/TokyoNight-SE.tar.bz2"
    dest: "{{ user_icons_path }}"
    remote_src: true

- name: Extract font archive
  ansible.builtin.unarchive:
    src: "{{ user_nerdfonts_url }}"
    dest: "{{ user_fonts_path }}"
    remote_src: true
    exclude:
      - README.md
      - SIL Open Font License.txt

- name: Extract Cursor Theme Archive
  ansible.builtin.unarchive:
    src: "https://github.com/catppuccin/cursors/releases/download/v0.3.1/catppuccin-mocha-dark-cursors.zip"
    dest: "{{ user_icons_path }}"
    remote_src: true
