---
- name: Create user to install AUR packages
  become: true
  ansible.builtin.user:
    name: aur_builder
  tags:
    - packages

- name: Add aur_builder to sudoers
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/aur_builder-allow-to-sudo-pacman
    state: present
    line: aur_builder ALL=(ALL) NOPASSWD:/usr/bin/pacman
    validate: /usr/sbin/visudo -cf %s
    create: true
    mode: '0644'
  tags:
    - packages

- name: Install Packages
  become_user: aur_builder
  become: true
  community.general.pacman:
    name: "{{ item }}"
    state: present
    executable: yay
  with_items: 
    - "{{ packages_common_packages }}"
    - "{{ packages_list }}"
    - "{{ packages_desktop }}"
    - "{{ packages_desktop_wm[desktop_wm] }}"
  tags:
    - packages
