---
- name: Include Flatpak Package variables
  ansible.builtin.include_vars: flatpak.yml
  tags:
    - flatpak

- name: Add flathub flatpak remote
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
  tags:
    - flatpak

- name: Add flatpak packages from flathub
  community.general.flatpak:
    name: "{{ packages_flatpak_packages }}"
    state: latest
  tags:
    - flatpak
