---
- name: Install Common Packages
  become: true
  ansible.builtin.package:
    name: "{{ packages_common_packages }}"
    state: present

- name: Include OS-specific Variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Install OS-specific Packages
  become: true
  ansible.builtin.package:
    name: "{{ packages_list }}"

- name: Handle Packages for Fedora
  ansible.builtin.include_tasks: fedora.yml
  when: ansible_os_family == 'RedHat'

- name: Handle Packages for Arch Linux
  ansible.builtin.include_tasks: archlinux.yml
  when: ansible_os_family == 'Archlinux'
