---
- name: Include OS-specific Variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Handle Packages
  ansible.builtin.include_tasks:
    - "{{ ansible_os_family }}.yml"
    - flatpak.yml
  tags:
    - packages
