---
- name: Include OS-specific Variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - packages

- name: Handle Packages
  block:
    - name: Handle OS specific packages
      ansible.builtin.include_tasks: "{{ ansible_os_family }}.yml"
    - name: Handle Flatpak packages
      ansible.builtin.include_tasks: flatpak.yml
  tags:
    - packages
