---
- name: Include Fedora specific roles
  ansible.builtin.include_role:
    name: "{{ item }}"
  loop:
    - rpmfusion

- name: Include OS-specific Variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Install Fusion Repo GPG Keys
  become: true
  ansible.builtin.rpm_key:
    key: "{{ packages_rpmfusion_keys_base_url }}RPM-GPG-KEY-rpmfusion-{{ item }}-{{ ansible_distribution | lower }}-2020"
    state: present
  loop: "{{ packages_rpmfusion_repo_types }}"

- name: Install RPM Fusion Repo Packages
  become: true
  vars:
    distribution: "{{ ansible_distribution | lower }}"
  ansible.builtin.dnf:
    name: "{{ packages_rpmfusion_repo_base_url }}/{{ item }}/{{ distribution }}/rpmfusion-{{ item }}-release-{{ ansible_distribution_version }}.noarch.rpm"
    state: present
  loop: "{{ packages_rpmfusion_repo_types }}"

- name: Enable Copr repos
  become: true
  community.general.copr:
    state: enabled
    name: "{{ item }}"
  loop: "{{ packages_copr_repos_list }}"

- name: Add Charm repository
  become: true
  ansible.builtin.yum_repository:
    name: Charm
    description: Repository to install Glow
    baseurl: https://repo.charm.sh/yum/
    enabled: true
    gpgcheck: true
    gpgkey: https://repo.charm.sh/yum/gpg.key

- name: Install Common Packages
  become: true
  ansible.builtin.package:
    name: "{{ packages_common_packages }}"
    state: present

- name: Install OS-specific Packages
  become: true
  ansible.builtin.package:
    name: "{{ packages_list }}"
    state: present

- name: Install Common Desktop Window Manager Packages
  become: true
  ansible.builtin.package:
    name: "{{ packages_desktop }}"
    state: present

- name: Install Desktop Window Manager
  become: true
  ansible.builtin.package:
    name: "{{ packages_desktop_wm[desktop_wm] }}"
    state: present

- name: Install DNF Group Packages
  become: true
  ansible.builtin.dnf:
    name: "{{ packages_dnf_groups }}"
    state: present

- name: Install Intel Media Driver for Intel Integrated GPU
  become: true
  ansible.builtin.dnf:
    name: intel-media-driver
    state: present

- name: Set system to use fedora-cisco-openh264
  become: true
  community.general.dnf_config_manager:
    name: fedora-cisco-openh264
    state: enabled

- name: Remove ffmpeg-free
  become: true
  ansible.builtin.dnf:
    name: ffmpeg-free
    state: absent

- name: Install ffmpeg
  become: true
  ansible.builtin.dnf:
    name: ffmpeg
    state: present
    allowerasing: true

- name: Update multimedia group
  become: true
  ansible.builtin.dnf:
    name: "@multimedia"
    state: present
    install_weak_deps: false
    exclude: PackageKit-gstreamer-plugin

- name: Install Crossover for Linux
  become: true
  ansible.builtin.dnf:
    name: "{{ packages_crossover_url }}"
    state: present
    disable_gpg_check: true
