import ranger as ranger
from ranger.core.linemode import LinemodeBase as LinemodeBase

__all__ = ['ranger', 'LinemodeBase', 'hook_init', 'hook_ready', 'register_linemode']

def hook_init(fm) -> None: ...
def hook_ready(fm) -> None: ...
def register_linemode(linemode_class): ...
