from _typeshed import Incomplete
from ranger.core.shared import FileManagerAware as FileManagerAware

ALLOWED_KEYS: Incomplete

class Bookmarks(FileManagerAware):
    last_mtime: Incomplete
    autosave: bool
    load_pattern: Incomplete
    dct: Incomplete
    original_dict: Incomplete
    path: Incomplete
    bookmarktype: Incomplete
    nonpersistent_bookmarks: Incomplete
    def __init__(self, bookmarkfile, bookmarktype=..., autosave: bool = False, nonpersistent_bookmarks=()) -> None: ...
    def load(self) -> None: ...
    def enter(self, key): ...
    def update_if_outdated(self) -> None: ...
    def remember(self, value) -> None: ...
    def __delitem__(self, key) -> None: ...
    def __iter__(self): ...
    def __getitem__(self, key): ...
    def __setitem__(self, key, value) -> None: ...
    def __contains__(self, key) -> bool: ...
    def update_path(self, path_old, file_new) -> None: ...
    def update(self) -> None: ...
    def save(self) -> None: ...
    def enable_saving_backtick_bookmark(self, boolean) -> None: ...
