from _typeshed import Incomplete
from ranger.container.fsobject import FileSystemObject as FileSystemObject

N_FIRST_BYTES: int
CONTROL_CHARACTERS: Incomplete
PREVIEW_BLACKLIST: Incomplete
PREVIEW_WHITELIST: Incomplete

class File(FileSystemObject):
    is_file: bool
    preview_data: Incomplete
    preview_known: bool
    preview_loading: bool
    @property
    def firstbytes(self): ...
    def is_binary(self): ...
    def has_preview(self): ...
    def get_preview_source(self, width, height): ...
    def is_image_preview(self): ...
    def __eq__(self, other): ...
    def __neq__(self, other): ...
    def __hash__(self): ...
