from _typeshed import Incomplete

class HistoryEmptyException(Exception): ...

class History:
    history: Incomplete
    index: Incomplete
    maxlen: Incomplete
    unique: Incomplete
    def __init__(self, maxlen: Incomplete | None = None, unique: bool = True) -> None: ...
    def add(self, item) -> None: ...
    def modify(self, item, unique: bool = False) -> None: ...
    def rebase(self, other_history) -> None: ...
    def __len__(self) -> int: ...
    def current(self): ...
    def top(self): ...
    def bottom(self): ...
    def back(self): ...
    def move(self, n): ...
    def search(self, string, n): ...
    def __iter__(self): ...
    def forward(self): ...
    def fast_forward(self) -> None: ...
