from _typeshed import Incomplete

ALLOWED_KEYS: Incomplete

class Tags:
    default_tag: str
    def __init__(self, filename) -> None: ...
    def __contains__(self, item) -> bool: ...
    def add(self, *items, **others) -> None: ...
    def remove(self, *items) -> None: ...
    def toggle(self, *items, **others) -> None: ...
    def marker(self, item): ...
    tags: Incomplete
    def sync(self) -> None: ...
    def dump(self) -> None: ...
    def update_path(self, path_old, path_new) -> None: ...
    def __nonzero__(self): ...
    __bool__ = __nonzero__

class TagsDummy(Tags):
    tags: Incomplete
    def __init__(self, filename) -> None: ...
    def __contains__(self, item) -> bool: ...
    def add(self, *items, **others) -> None: ...
    def remove(self, *items) -> None: ...
    def toggle(self, *items, **others) -> None: ...
    def marker(self, item): ...
    def sync(self) -> None: ...
    def dump(self) -> None: ...
