---
- name: Create a greeter user and add them to the 'video' group
  become: true
  ansible.builtin.user:
    name: "{{ greetd_user }}"
    groups: "{{ greetd_group }}"
    create_home: false
    append: true
    state: present

- name: Remove existing config.toml that may have been installed
  become: true
  ansible.builtin.file:
    name: "{{ greetd_dir }}/config.toml"
    state: absent

- name: Copy files to /etc/greetd
  become: true
  ansible.builtin.copy:
    src: "files/{{ item }}"
    dest: "{{ greetd_dir }}/{{ item }}"
    owner: "{{ greetd_user }}"
    group: "{{ greetd_group }}"
    mode: "{{ greetd_mode }}"
  loop:
    - gtk-dark.css
    - "{{ desktop_wm }}.conf"

- name: Populate config.toml template
  ansible.builtin.template:
    src: templates/config.toml.j2
    dest: "{{ greetd_dir }}/config.toml"
    owner: "{{ greetd_user }}"
    group: "{{ greetd_group }}"
    mode: "{{ greetd_mode }}"

- name: Disable SDDM
  become: true
  ansible.builtin.systemd:
    name: sddm
    enabled: false
  register: sddm_result
  failed_when: "'Could not find the requested service sddm' in sddm_result.msg"
  ignore_errors: true

- name: Enable greetd service
  become: true
  ansible.builtin.systemd:
    name: greetd
    enabled: true
