---
- name: Create a greeter user and add them to the 'video' group
  become: true
  ansible.builtin.user:
    name: greeter
    state: present
    create_home: false
    groups: video
    append: true

- name: Remove existing config.toml that may have been installed
  become: true
  ansible.builtin.file:
    name: /etc/greetd/config.toml
    state: absent

- name: Copy files to /etc/greetd
  become: true
  ansible.builtin.copy:
    src: "files/{{ item }}"
    dest: "/etc/greetd/{{ item }}"
    mode: '0644'
    owner: greeter
    group: greeter
  loop:
    - config.toml
    - gtk-dark.css
    - sway-config

- name: Disable SDDM
  become: true
  ansible.builtin.systemd:
    name: sddm
    enabled: false
  register: sddm_result
  failed_when: "'Could not find the requested service sddm' in sddm_result.msg"
  ignore_errors: true

- name: Enable greetd service
  become: true
  ansible.builtin.systemd:
    name: greetd
    enabled: true
