from _typeshed import Incomplete
from ranger.ext.direction import Direction as Direction

class Accumulator:
    pointer: int
    pointed_obj: Incomplete
    def __init__(self) -> None: ...
    def move(self, narg: Incomplete | None = None, **keywords): ...
    def move_to_obj(self, arg, attr: Incomplete | None = None): ...
    def correct_pointer(self) -> None: ...
    def pointer_is_synced(self): ...
    def sync_index(self, **kw) -> None: ...
    @staticmethod
    def get_list(): ...
    @staticmethod
    def get_height(): ...
