from _typeshed import Incomplete

class Direction(dict):
    def __init__(self, dictionary: Incomplete | None = None, **keywords) -> None: ...
    def copy(self): ...
    def up(self): ...
    def down(self): ...
    def right(self): ...
    def absolute(self): ...
    def left(self): ...
    def relative(self): ...
    def vertical_direction(self): ...
    def horizontal_direction(self): ...
    def vertical(self): ...
    def horizontal(self): ...
    def pages(self): ...
    def percentage(self): ...
    def cycle(self): ...
    def one_indexed(self): ...
    def multiply(self, n) -> None: ...
    def set(self, n) -> None: ...
    def move(self, direction, override: Incomplete | None = None, minimum: int = 0, maximum: int = 9999, current: int = 0, pagesize: int = 1, offset: int = 0): ...
    def move_cycles(self): ...
    def select(self, lst, current, pagesize, override: Incomplete | None = None, offset: int = 1): ...
