from _typeshed import Incomplete
from collections.abc import Generator
from ranger.core.shared import FileManagerAware as FileManagerAware

W3MIMGDISPLAY_ENV: str
W3MIMGDISPLAY_OPTIONS: Incomplete
W3MIMGDISPLAY_PATHS: Incomplete

def temporarily_moved_cursor(to_y, to_x) -> Generator[None]: ...
def move_cur(to_y, to_x) -> None: ...

class ImageDisplayError(Exception): ...
class ImgDisplayUnsupportedException(Exception): ...

def fallback_image_displayer() -> None: ...

IMAGE_DISPLAYER_REGISTRY: Incomplete

def register_image_displayer(nickname: Incomplete | None = None): ...
def get_image_displayer(registry_key): ...

class ImageDisplayer:
    working_dir: Incomplete
    def draw(self, path, start_x, start_y, width, height) -> None: ...
    def clear(self, start_x, start_y, width, height) -> None: ...
    def quit(self) -> None: ...

class W3MImageDisplayer(ImageDisplayer, FileManagerAware):
    is_initialized: bool
    binary_path: Incomplete
    process: Incomplete
    def __init__(self) -> None: ...
    def initialize(self) -> None: ...
    def draw(self, path, start_x, start_y, width, height) -> None: ...
    def clear(self, start_x, start_y, width, height) -> None: ...
    def quit(self) -> None: ...

class ITerm2ImageDisplayer(ImageDisplayer, FileManagerAware):
    def draw(self, path, start_x, start_y, width, height) -> None: ...
    def clear(self, start_x, start_y, width, height) -> None: ...
    def quit(self) -> None: ...

class TerminologyImageDisplayer(ImageDisplayer, FileManagerAware):
    display_protocol: str
    close_protocol: str
    def __init__(self) -> None: ...
    def draw(self, path, start_x, start_y, width, height) -> None: ...
    def clear(self, start_x, start_y, width, height) -> None: ...
    def quit(self) -> None: ...

class URXVTImageDisplayer(ImageDisplayer, FileManagerAware):
    display_protocol: str
    close_protocol: str
    def __init__(self) -> None: ...
    def draw(self, path, start_x, start_y, width, height) -> None: ...
    def clear(self, start_x, start_y, width, height) -> None: ...
    def quit(self) -> None: ...

class URXVTImageFSDisplayer(URXVTImageDisplayer): ...

class KittyImageDisplayer(ImageDisplayer, FileManagerAware):
    protocol_start: bytes
    protocol_end: bytes
    stdbout: Incomplete
    stdbin: Incomplete
    image_id: int
    fsenc: Incomplete
    needs_late_init: bool
    backend: Incomplete
    stream: Incomplete
    def __init__(self) -> None: ...
    def draw(self, path, start_x, start_y, width, height) -> None: ...
    def clear(self, start_x, start_y, width, height) -> None: ...
    def quit(self) -> None: ...

class UeberzugImageDisplayer(ImageDisplayer):
    IMAGE_ID: str
    is_initialized: bool
    process: Incomplete
    def __init__(self) -> None: ...
    def initialize(self) -> None: ...
    def draw(self, path, start_x, start_y, width, height) -> None: ...
    def clear(self, start_x, start_y, width, height) -> None: ...
    def quit(self) -> None: ...
