from _typeshed import Incomplete
from collections.abc import Generator
from shutil import Error as Error, SpecialFileError as SpecialFileError, rmtree as rmtree

__all__ = ['copyfileobj', 'copyfile', 'copystat', 'copy2', 'BLOCK_SIZE', 'copytree', 'move', 'rmtree', 'Error', 'SpecialFileError']

BLOCK_SIZE: Incomplete

def copystat(src, dst, follow_symlinks: bool = True): ...
def copyfileobj(fsrc, fdst, length=...) -> Generator[Incomplete]: ...
def copyfile(src, dst) -> Generator[Incomplete]: ...
def copy2(src, dst, overwrite: bool = False, symlinks: bool = False, make_safe_path=...) -> Generator[Incomplete]: ...
def copytree(src, dst, symlinks: bool = False, ignore: Incomplete | None = None, overwrite: bool = False, make_safe_path=...) -> Generator[Incomplete]: ...
def move(src, dst, overwrite: bool = False, make_safe_path=...) -> Generator[Incomplete]: ...
