[Personal]
source            = imaps://william%40williamgsmith.co.za@mail.williamgsmith.co.za:993
source-cred-cmd   = rbw get "webmail.williamgsmith.co.za"
outgoing          = smtp://william%40williamgsmith.co.za@smtp.williamgsmith.co.za:587
outgoing-cred-cmd = rbw get "webmail.williamgsmith.co.za"
default           = INBOX
exclude-folders   = Starred$,spam$,Notes$
from              = William Smith <william@williamgsmith.co.za>
copy-to           = Sent
cache-headers     = true
