#
# aerc main configuration

[general]
default-save-path=~/Downloads/
term=tmux-256color
enable-osc8=false
default-menu-cmd=fzf

[ui]
index-columns=star:1,name<20%,reply:1,subject,size>=,date>=
column-star = {{if .IsFlagged}}󰉀 {{end}}
column-reply = {{if .IsReplied}} {{else if .IsForwarded}} {{end}}
column-subject = {{.Style .ThreadPrefix "thread"}}{{.Subject}}
column-size = {{if .HasAttachment}}󰏢 {{end}}{{humanReadable .Size}}
column-name = {{.Peer | names | join ", "}}

sidebar-width=30

pinned-tab-marker='󰐃'

dirlist-right={{if .Unread}}{{humanReadable .Unread}}{{end}}{{if .Exists}}{{humanReadable .Exists}}{{end}}
dirlist-tree=true
dirlist-collapse=0

sort=-r date

next-message-on-delete=true
auto-mark-read=true

border-char-vertical="│"
border-char-horizontal="─"

styleset-name=catppuccin-macchiato

fuzzy-complete=true
completion-delay=250ms
completion-popovers=true

sort-thread-siblings=true
threading-enabled=true
thread-prefix-tip = ">"

[statusline]
display-mode=icon

[viewer]
pager=bat --wrap auto -p
alternatives=text/html,text/plain
header-layout=From,To,Subject,Cc,Bcc
always-show-mime=true
parse-http-links=true

[compose]
header-layout=From,To,Subject,Cc,Date
edit-headers=false
reply-to-self=false
empty-subject-warning=true
no-attachment-warning=^[^>]*attach(ed|ment)
format-flowed=false

[multipart-converters]
text/html=pandoc -f markdown -t html --standalone

[filters]
.filename,~,.md$=glow --width "$(tput cols)"
.headers=colorize

application/*=bat -fP --file-name="$AERC_FILENAME"
message/delivery-status=colorize
message/rfc822=colorize
text/calendar=calendar
text/html=! html
text/markdown=glow --width "$(tput cols)"
text/plain=colorize
text/x-diff=! delta
text/x-patch=! delta
text/*=bat -fP --file-name="$AERC_FILENAME"

[openers]
application/pdf=zathura
*.xlsx=et
*.docx=wps

[hooks]
# Executed when a new email arrives in the selected folder
mail-received=notify-send \
                --urgency=normal \
                "New email from $AERC_FROM_NAME <$AERC_FROM_ADDRESS>" \
                "$AERC_SUBJECT"

[templates]
