---
# tasks file for ssh
- name: Copy ssh config to ~/.ssh/config
  ansible.builtin.copy:
    src: "files/config"
    dest: "{{ ansible_env.HOME }}/.ssh/config"
    mode: '0644'
  tags:
    - ssh

- name: Copy systemd files to ~/.config/system/user/
  ansible.builtin.copy:
    src: "files/ssh-agent.service"
    dest: "{{ ansible_env.HOME }}/.config/systemd/user/ssh-agent.service"
    mode: '0644'
  tags:
    - ssh

- name: Add SSH_AUTH_SOCK to ~/.pam-environment
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.pam-environment"
    state: present
    mode: '0644'
    create: true
    line: 'SSH_AUTH_SOCK DEFAULT="${XDG_RUNTIME_DIR}/ssh-agent.socket"'
  tags:
    - ssh

- name: Make sure the ssh-agent service is started and enabled
  ansible.builtin.systemd:
    name: ssh-agent
    state: started
    enabled: true
    daemon_reload: true
    scope: user
  tags:
    - ssh
