[terminal]
vt = 1

[default_session]
command = "tuigreet --user-menu --time --remember --remember-user-session asterisks --cmd /usr/local/bin/sway"
user = "greeter"

[initial_session]
command = "/usr/local/bin/sway"
user = "williamsmith"
