---
# tasks file for nerdfonts
- name: Extract font archive
  ansible.builtin.unarchive:
    src: "{{ nerdfonts_url }}"
    dest: "{{ ansible_env.HOME }}/.local/share/fonts/"
    remote_src: true
    exclude:
      - README.md
      - SIL Open Font License.txt
