---
stow_dir: "{{ ansible_env.HOME }}"
stow_packages:
  - alacritty
  - zsh
  - gtk-2.0
  - gtk-3.0
  - gtk-4.0
  - Kvantum
  - mako
  - nwg-look
  - qt5ct
  - qt6ct
  - xresources
  - xsettingsd
  - git
  - starship
  - bat
  - cheat
  - delta
  - direnv
  - fd
  - khard
  - khal
  - lazygit
  - nvim
  - ranger
  - ripgrep
  - zathura
  - rofi
  - sway
  - swaylock
  - swaynag
  - waybar
