# Example special workspace (scratchpad)
bind = $mainMod, Z, togglespecialworkspace, magic
bind = $mainMod SHIFT, Z, movetoworkspace, special:magic

bind = $mainMod SHIFT, Return, exec, pypr toggle term
bind = $mainMod SHIFT, V, exec, pypr-client toggle volume
bind = $mainMod SHIFT, B, exec, pypr-client toggle bluetooth
bind = $mainMod SHIFT, O, exec, pypr-client toggle Outlook
bind = $mainMod SHIFT, T, exec, pypr-client toggle Teams
