pyprland.plugins = ["scratchpads"]

[scratchpads.term]
animation = "fromTop"
command = "[term_classed] dropterm"
class = "dropterm"
size = "75% 60%"
max_size = "1920px 100%"
unfocus = "hide"

[scratchpads.Outlook]
command = "firefox --new-window 'ext+container:name=Work&url=https://outlook.office365.com'"
match_by = "title"
title = "re:.*Outlook.*Mozilla Firefox"
size = "50% 90%"
lazy = true

[scratchpads.Teams]
command = "firefox --new-window 'ext+container:name=Work&url=https://teams.microsoft.com'"
size = "50% 90%"
match_by = "title"
title = "re:.*Microsoft Teams.*Mozilla Firefox"
lazy = true

[scratchpads.volume]
command = "pavucontrol"
animation = "fromTop"
size = "25% 35%"
lazy = true

[scratchpads.bluetooth]
command = "blueman-manager"
animation = "fromTop"
size = "25% 35%"
lazy = true
