---
- name: Get Repolist
  ansible.builtin.command: "dnf repolist"
  register: dnf_repolist
  changed_when: false

- name: Checking if Git LFS repo has been added
  ansible.builtin.set_fact:
    git_lfs_repo_added: "{{ 'true' if (dnf_repolist.stdout | regex_search('git-lfs')) else 'false' }}"

- name: Download Git LFS installation script
  ansible.builtin.get_url:
    url: "{{ git_lfs_repo_url }}"
    dest: "{{ git_lfs_script_path }}"
    mode: '0755'
  when: git_lfs_repo_added == 'false'

- name: Run Git LFS repo installation script
  become: true
  ansible.builtin.command: "{{ git_lfs_script_path }}"
  when: git_lfs_repo_added == 'false'
  register: git_lfs_installation
  changed_when: '"The repository is setup! You can now install packages." in git_lfs_installation.stdout'
