---
- name: Install Git
  ansible.builtin.package:
    name:
      - git
      - golang
    state: present
  tags:
    - git

- name: Clone lfs-test-server repository
  become: true
  ansible.builtin.git:
    repo: https://github.com/git-lfs/lfs-test-server.git
    dest: /opt/lfs-test-server
    version: main
  tags:
    - git

- name: Build git-lfs
  become: true
  ansible.builtin.command:
    cmd: go build
  args:
    chdir: /opt/git-lfs
    creates: /opt/git-lfs/git-lfs
  tags:
    - git

- name: Build lfs-test-server
  become: true
  ansible.builtin.command:
    cmd: go build
  args:
    chdir: /opt/lfs-test-server
    creates: /opt/lfs-test-server/lfs-test-server
  tags:
    - git

- name: Create LFS configuration directory
  become: true
  ansible.builtin.file:
    path: /etc/lfs-test-server
    state: directory
    mode: '0755'
  tags:
    - git

- name: Create Configuration file
  become: true
  ansible.builtin.template:
    src: files/config.yml.j2
    dest: /etc/lfs-test-server/config.yml
    mode: '0644'
  tags:
    - git

- name: Create systemd service file
  become: true
  ansible.builtin.copy:
    src: files/lfs-test-server.service
    dest: /etc/systemd/system/lfs-test-server.service
    mode: '0644'
  tags:
    - git

- name: Reload systemd daemon
  become: true
  ansible.builtin.systemd:
    name: lfs-test-server
    enabled: true
    daemon_reload: true
    state: started
  tags:
    - git
