palette = "catppuccin_macchiato"

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

add_newline = "false"
command_timeout = "4000"
scan_timeout = "10"
continuation_prompt = '󰁔 '

format = """
$username\
$hostname\
$battery\
$directory\
$cmake\
$python\
$vagrant\
$docker_context\
$env_var\
$time\
$status
$character"""

right_format = """
$git_branch\
$git_status\
$git_metrics\
$git_state\
$git_commit
"""

[battery]
full_symbol = '󰁹'
charging_symbol = '󰂄'
discharging_symbol = '󰂃'
empty_symbol = '󰂎'
format = '[$symbol\($percentage\) ]($style)'

[[battery.display]]
threshold = 10
style = 'bold red'

[[battery.display]]
threshold = 20
style = 'bold orange'

[[battery.display]]
threshold = 30
style = 'bold yellow'

[[battery.display]]
threshold = 99
style = 'bold green'

[character]
success_symbol = '[](bold bright-blue)[](bold blue)'
error_symbol = '[](bold bright-red)[](bold blue)'
vimcmd_symbol = '[](bold bright-cyan)[](bold blue)'

[directory]
truncation_length = 2
truncation_symbol = ".../"
truncate_to_repo = true
style = 'bold blue'
format = '[󰉋 ](style)[$path]($style)[$read_only ]($read_only_style)'
read_only = '󰌾 '
home_symbol = '󰋜 '

[git_branch]
format = '[$symbol$branch ]($style)'
symbol = '󰘬 '

[git_state]
format = '\(:[$state( $progress_current/$progress_total)]($style)\)'

[git_status]
format = '([$all_status$ahead_behind]($style))'
conflicted = '\[󰞇 [$count](bright-white bold)\]]'
ahead = '\[[󱦲](bright-blue)[$count](bright-white bold)\]'
behind = '\[[󱦳]](white)[$count](bright-white bold)\]'
diverged = '\[[󰃻](purple)|[󱦲](bright-blue)[$ahead_count][󱦳](white)[$behind_count](bright-white)\]'
untracked = '\[󰡯 [$count](bright-white bold)\]'
stashed = '\[[󰆓](yellow) [$count](bright-white bold)\]'
modified = '\[󰭎 (bright-yellow)[$count](bright-white bold)\]'
staged = '\[[󰄬](bright-green)[$count](bright-white bold)\]'
renamed = '\[[󰑕](bright-cyan) [$count](bright-white bold)\]'
deleted = '\[ [$count](bright-white bold)\]'

[git_commit]
commit_hash_length = 8
style = 'bold white'
tag_symbol = '󰓹 '

[hostname]
ssh_only = false
disabled = true

[status]
disabled = false
symbol = ' '

[username]
style_user = "green bold"
style_root = "black bold"
format = "[$user ]($style)"
disabled = false
show_always = true
