---
asdf_version: v0.14.1
asdf_git_url: https://github.com/asdf-vm/asdf.git
asdf_dir: "{{ ansible_env.HOME }}/.asdf"
asdf_source_script: "{{ asdf_dir }}/asdf.sh"
asdf_plugins:
  - deno
  - github-cli
