from ranger.core.main import allow_access_to_confdir as allow_access_to_confdir
from ranger.ext.cached_function import cached_function as cached_function
from ranger.ext.iter_tools import flatten as flatten
from ranger.gui.color import get_color as get_color
from ranger.gui.context import Context as Context

class ColorSchemeError(Exception): ...

class ColorScheme:
    def get(self, *keys): ...
    def get_attr(self, *keys): ...
    @staticmethod
    def use(_): ...

def get_all_colorschemes(fm): ...
