from _typeshed import Incomplete
from ranger.core.shared import SettingsAware as SettingsAware
from ranger.gui.color import get_color as get_color

REVERSE_ADDCH_ARGS: Incomplete

class CursesShortcuts(SettingsAware):
    win: Incomplete
    def __init__(self) -> None: ...
    def addstr(self, *args) -> None: ...
    def addnstr(self, *args) -> None: ...
    def addch(self, *args) -> None: ...
    def color(self, *keys) -> None: ...
    def color_at(self, y, x, wid, *keys) -> None: ...
    def set_fg_bg_attr(self, fg, bg, attr) -> None: ...
    def color_reset(self) -> None: ...
