from _typeshed import Incomplete

class MouseEvent:
    PRESSED: Incomplete
    CTRL_SCROLLWHEEL_MULTIPLIER: int
    def __init__(self, getmouse) -> None: ...
    def pressed(self, n): ...
    def mouse_wheel_direction(self): ...
    def ctrl(self): ...
    def alt(self): ...
    def shift(self): ...
    def key_invalid(self): ...
