general {
    hide_cursor = true
    ignore_empty_input = true  # matches your ignore-empty-password
    screencopy_mode = 1
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fade, 1, 1.8, linear  # matches your fade-in=2
}

background {
    monitor =
    path = screenshot
    color = rgb(24273a)       # your original color= from swaylock config
    blur_passes = 3
    blur_size = 7
    brightness = 0.75
}

render {
  explicit_sync = 0
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 5    # matches indicator-thickness=10em
    dots_size = 0.33
    dots_spacing = 0.15
    outer_color = rgb(b7bdf8)         # ring-color
    inner_color = rgba(0, 0, 0, 0.0) # inside-color
    font_color = rgb(cad3f5)          # text-color
    font_family = Iosevka NFP Light
    fade_on_empty = false
    placeholder_text =
    check_color = rgb(8aadf4)         # ring-ver-color
    fail_color = rgb(ee99a0)          # ring-wrong-color
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    capslock_color = rgb(f5a97f)      # ring-caps-lock-color
    rounding = -1
    position = 0, -20
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    color = rgb(cad3f5)
    font_size = 32
    font_family = Iosevka NFP Light
    position = 0, 80
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] date +"%a, %d %b %Y"
    color = rgb(cad3f5)
    font_size = 22
    font_family = Iosevka NFP Light
    position = 0, 40
    halign = center
    valign = center
}
