local vars = require("vars")

hl.on("hyprland.start", function()
	hl.exec_cmd("dbus-update-activation-environment --systemd --all")
	hl.exec_cmd("systemctl --user import-environment --all")
	hl.exec_cmd("systemctl --user start hyprpolkitagent")
	hl.exec_cmd("mako")
	hl.exec_cmd("waybar")
	hl.exec_cmd("nm-applet --indicator")
	hl.exec_cmd("blueman-applet")
	hl.exec_cmd("wl-paste --type text --watch cliphist store")
	hl.exec_cmd("wl-paste --type image --watch cliphist store")
	hl.exec_cmd("/usr/bin/pypr --debug /tmp/pypr.log")
	hl.exec_cmd("hyprpaper")
	hl.exec_cmd(vars.terminal)
end)
