windowrule = match:class ^(org.mozilla.firefox)$, suppress_event maximize

windowrule = match:title ^(Firefox - Sharing Indicator)$, float on

windowrule = match:title ^(Firefox - Sharing Indicator)$, float on
