windowrule = match:title ^(Open|Choose Files|Save As)$, float on

windowrule = match:class ^(nwg-look)$, float on

windowrule = match:class ^(nm-connection-editor)$, float on

windowrule = match:class ^(python3)$, float on

windowrule = match:class ^(file_progress)$, float on

windowrule = match:class ^(confirm)$, float on

windowrule = match:class ^(dialog)$, float on

windowrule = match:class ^(notification)$, float on

windowrule = match:class ^(error)$, float on

windowrule = match:class ^(confirmreset)$, float on

windowrule = match:title ^(Confirm to replace files)$, float on

windowrule = match:title ^(File Operation Progress)$, float on

windowrule = match:title ^(wdisplays)$, float on

