windowrule = match:title ^(fly_is_foot)$, float on
windowrule = match:title ^(fly_is_foot)$, center on
windowrule = match:title ^(fly_is_foot)$, size 860 640

windowrule = match:title (dropterm), float on
windowrule = match:title (dropterm), workspace special:scratch_term silent
