$pip = ^([Pp]icture[\s\-]in[\s\-][Pp]icture)$

windowrule = match:title $pip, float on
windowrule = match:title $pip, center on
windowrule = match:title $pip, size 25% 25%
windowrule = match:title $pip, move 74% 10%
windowrule = match:title $pip, rounding 0
windowrule = match:class $pip, pin on

