from .vcs import Vcs as Vcs, VcsError as VcsError
from _typeshed import Incomplete

def string_control_replace(string, replacement): ...

class Git(Vcs):
    def action_add(self, filelist: Incomplete | None = None) -> None: ...
    def action_reset(self, filelist: Incomplete | None = None) -> None: ...
    def data_status_root(self): ...
    def data_status_subpaths(self): ...
    def data_status_remote(self): ...
    def data_branch(self): ...
    def data_info(self, rev: Incomplete | None = None): ...
