---
- name: Copy Sway files
  become: true
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0644'
  loop: "{{ sway_paths }}"

- name: Create overriding files
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/sway/conf.d/{{ item }}"
    state: touch
    mode: '0644'
  loop:
    - "90-bar.conf"
    - "95-autostart-policykit-agent.conf"
    - "95-xdg-desktop-autostart.conf"
  when: ansible_os_family == 'RedHat'
