---
- name: Copy Sway files
  become: true
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0644'
  loop: "{{ sway_paths }}"

- name: Create overriding files
  ansible.builtin.file:
    path: "{{ ansible_env.XDG_CONFIG_HOME }}/sway/config.d/{{ item }}"
    state: touch
    mode: '0644'
  loop:
    - "90-bar.conf"
    - "95-autostart-policykit-agent.conf"
    - "95-xdg-desktop-autostart.conf"
  when: ansible_os_family == 'RedHat'

- name: Creating overriding files
  ansible.builtin.file:
    path: "{{ ansible_env.XDG_CONFIG_HOME }}/sway/config.d/{{ item }}"
    state: touch
    mode: '0644'
  loop:
    - "95-system-keyboard-config.conf"
    - "95-xdg-desktop-autostart.conf"
  when: ansible_os_family == 'Archlinux'

- name: Creating startup config for sway
  ansible.builtin.template:
    src: templates/30-startup.conf.j2
    dest: "{{ ansible_env.XDG_CONFIG_HOME }}/sway/config.d/30-startup.conf"
    mode: '0644'
