---
- name: Remove pulseaudio packages
  become: true
  ansible.builtin.package:
    name:
      - pulseaudio-ctl
      - pulseaudio-alsa
      - pulseaudio-bluetooth
      - pulseaudio-zeroconf
      - pulseaudio-qt
      - pulseaudio
    state: absent
  tags:
    - pipewire

- name: Install pipewire packages
  become: true
  ansible.builtin.package:
    name:
      - pavucontrol
      - pipewire
      - pipewire-pulse
      - pipewire-alsa
      - pipewire-jack
      - wireplumber
      - sof-firmware
    state: present
  tags:
    - pipewire