---
- name: Remove pulseaudio packages
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: absent
  with_items:
    - pulseaudio-ctl
    - pulseaudio-alsa
    - pulseaudio-bluetooth
    - pulseaudio-zeroconf
    - pulseaudio-qt
    - pulseaudio
  tags:
    - pipewire

- name: Install pipewire packages
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - pavucontrol
    - pipewire
    - pipewire-pulse
    - pipewire-alsa
    - pipewire-jack
    - wireplumber
    - sof-firmware
  tags:
    - pipewire
