---
- name: Remove pulseaudio packages
  become: true
  ansible.builtin.package:
    name:
      - pulseaudio-ctl
      - pulseaudio-alsa
      - pulseaudio-bluetooth
      - pulseaudio-zeroconf
      - pulseaudio-qt
      - pulseaudio
  tags:
    - pipewire

- name: Install pipewire packages
  become: true
  ansible.builtin.package:
    name:
      - pipewire
      - pipewire-pulsedio
      - wireplumber
  tags:
    - pipewire
