from . import Widget as Widget
from _typeshed import Incomplete
from ranger.ext.direction import Direction as Direction
from ranger.ext.img_display import ImgDisplayUnsupportedException as ImgDisplayUnsupportedException
from ranger.gui import ansi as ansi

LOG: Incomplete

class Pager(Widget):
    source: Incomplete
    source_is_stream: bool
    old_source: Incomplete
    old_scroll_begin: int
    old_startx: int
    need_clear_image: bool
    need_redraw_image: bool
    max_width: Incomplete
    embedded: Incomplete
    scroll_begin: int
    scroll_extra: int
    startx: int
    markup: Incomplete
    lines: Incomplete
    image: Incomplete
    image_drawn: bool
    def __init__(self, win, embedded: bool = False) -> None: ...
    need_redraw: bool
    def open(self) -> None: ...
    def clear_image(self, force: bool = False) -> None: ...
    def close(self) -> None: ...
    def destroy(self) -> None: ...
    def finalize(self) -> None: ...
    def scrollbit(self, lines) -> None: ...
    def draw(self) -> None: ...
    def draw_image(self) -> None: ...
    def move(self, narg: Incomplete | None = None, **kw) -> None: ...
    def press(self, key) -> None: ...
    def set_image(self, image) -> None: ...
    def set_source(self, source, strip: bool = False): ...
    def click(self, event): ...
