from . import Widget as Widget
from _typeshed import Incomplete
from ranger.ext.accumulator import Accumulator as Accumulator

class TaskView(Widget, Accumulator):
    old_lst: Incomplete
    scroll_begin: int
    def __init__(self, win) -> None: ...
    need_redraw: bool
    def draw(self) -> None: ...
    def finalize(self) -> None: ...
    def task_remove(self, i: Incomplete | None = None) -> None: ...
    def task_move(self, to, i: Incomplete | None = None) -> None: ...
    def press(self, key) -> None: ...
    def get_list(self): ...
