from . import Widget as Widget
from ..displayable import DisplayableContainer as DisplayableContainer
from _typeshed import Incomplete
from ranger.ext.keybinding_parser import key_to_string as key_to_string

class ViewBase(Widget, DisplayableContainer):
    draw_bookmarks: bool
    need_clear: bool
    draw_hints: bool
    draw_info: bool
    old_draw_borders: Incomplete
    columns: Incomplete
    main_column: Incomplete
    pager: Incomplete
    def __init__(self, win) -> None: ...
    def request_clear(self) -> None: ...
    need_redraw: bool
    def draw(self) -> None: ...
    def finalize(self) -> None: ...
    def click(self, event): ...
    def resize(self, y, x, hei: Incomplete | None = None, wid: Incomplete | None = None) -> None: ...
    def poke(self) -> None: ...
