---
- name: Printing nvim_config_path
  ansible.builtin.debug:
    msg: "{{ nvim_config_path }}"
  tags:
    - nvim

- name: Check if nvim has already received its config
  ansible.builtin.stat:
    path: "{{ nvim_config_path }}/lua"
  register: lua_link
  tags:
    - nvim

- name: Setup AstroNvim
  tags:
    - nvim
  block:
    - name: Clone AstroNvim
      ansible.builtin.git:
        repo: "{{ nvim_astronvim_url }}"
        dest: "{{ nvim_config_path }}"
        depth: 1
        version: main

    - name: Remove unnecessary directories from ~/.config/nvim
      ansible.builtin.file:
        name: "{{ item }}"
        state: absent
      loop:
        - "{{ nvim_config_path }}/.git"
        - "{{ nvim_config_path }}/lua"
